import type { Metadata } from 'next';
import { QuizProvider } from './context/QuizContext';
import { UserProvider } from './context/UserContext';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <QuizProvider>{children}</QuizProvider>
        </UserProvider>
      </body>
    </html>
  );
}
